config/routes.rb
Rails.application.routes.draw do
  match '*path' => 'options_request#preflight', via: :options

  devise_for :user, only: []

  namespace :api, defaults: { format: :json } do
    resource :login, only: [:create], controller: :sessions
    resource :users, only: [:create]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # resources :users do
  #   member do
  #     get :following, :followers
  #     get :favorite_posts
  #     post 'follow', to: 'users#follow'
  #     post 'unfollow', to: 'users#unfollow'
  #   end
  #   resources :posts do
  #     post 'favorite', to: 'users#favorite'
  #     post 'unfavorite', to: 'users#unfavorite'
  #   end
  # end

  # API
  namespace :api, format: 'json' do
    post '/users/follow/:user_id', to: 'users#follow'
    post '/users/unfollow/:user_id', to: 'users#unfollow'
    get '/users/isfollowing/:user_id', to: 'users#following?'
    post '/users/favorite/:post_id', to: 'users#favorite'
    post '/users/unfavorite/:post_id', to: 'users#unfavorite'
    get '/users/isfavorite/:post_id', to: 'users#favorite?'

    resources :users, only: [:index, :show] do
        get :following, :followers
        get :favorite_posts
      resources :posts, only: [:index, :show, :create] do
      end
    end
  end

  root to: 'home#index'

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  #include Devise::JWT::RevocationStrategies::JTIMatcher

  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  after_create :update_auth_token!

  mount_uploader :image, PhotoUploader

  has_many :posts
  has_many :favorites, dependent: :destroy
  has_many :favorite_posts, :through => :favorites, source: :post
  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                  foreign_key: "followed_id",
                                  dependent:   :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  def new
    
  end

  # Postをfavoriteする
  def favorite(post)
    favorites.create(post_id: post.id)
  end

  def unfavorite(post)
    favorites.find_by(post_id: post.id).destroy
  end

  def favorite?(post)
    return favorite_posts.include?(post)
  end

  # ユーザーをフォローする
  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  # ユーザーをアンフォローする
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # 現在のユーザーがフォローしてたらtrueを返す
  def following?(other_user)
    following.include?(other_user)
  end

  def on_jwt_dispatch(token, payload)
    self.update_attribute('jti',token)
  end

  def update_auth_token!
    self.auth_token = "#{self.id}:#{Devise.friendly_token}"
    save
  end
  
end

app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController
  skip_before_action :authenticate_user_from_token!, except: [:create, :follow, :unfollow]

  #GET
  def index
    @users = User.all
    render :json => @users, except:[:auth_token]
  end

  def show
    @user = User.find(params[:id])
    render :json => @user, except:[:auth_token]
  end

  def following
    @users = User.find(params[:user_id]).following
    render :json => @users, except:[:auth_token]
  end

  def followers
    @users = User.find(params[:user_id]).followers
    render :json => @users, except:[:auth_token]
  end

  def favorite_posts
    @posts = User.find(params[:user_id]).favorite_posts
    render :json => @posts
  end

  # POST
  # Create an user
  def create
    @user = User.new user_params

    if @user.save!
      render json: @user, root: nil
    else
      render json: { error: t('user_create_error') }, status: :unprocessable_entity
    end
  end

  def follow
    @user = User.find_by(auth_token: request.headers['Authorization'])
    @followed = User.find_by(id: params[:user_id])
    @user.follow(@followed)
    render json: { isfollowing: true }, root: nil
  end

  def unfollow
    @user = User.find_by(auth_token: request.headers['Authorization'])
    @followed = User.find_by(id: params[:user_id])
    @user.unfollow(@followed)
    render json: { isfollowing: false }, root: nil
  end

  def following?
    @user = User.find_by(auth_token: request.headers['Authorization'])
    if !@user
      render json: { status: 'false' }, status: 400
    end
    render json: { isfollowing: @user.following?(User.find_by(id: params[:user_id])) }, root: nil
  end

  def favorite
    @user = User.find_by(auth_token: request.headers['Authorization'])
    @post = Post.find_by(id: params[:post_id])
    @user.favorite(@post)
    render json: { status: 'true' }
  end

  def unfavorite
    @user = User.find_by(auth_token: request.headers['Authorization'])
    @post = Post.find_by(id: params[:post_id])
    @user.unfavorite(@post)
    render json: { status: 'true' }
  end

  def favorite?
    @user = User.find_by(auth_token: request.headers['Authorization'])
    if @user == nil
      render json: { status: 'false' }, status: 400
    else
      render json: { isFavorite: @user.favorite?(Post.find_by(id: params[:post_id])) }, root: nil
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :password, :email, :text, :image)
    end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  respond_to :json
  #layout 'static'
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   @user = current_user
  #   super do
  #     if request.format.json?
  #       render :json => {
  #         'status' => 'ok',
  #         'csrf_token' => form_authenticity_token,
  #         'result' => {
  #           'user' => {
  #             'id' => @user.id,
  #             'email' => @user.email
  #           }
  #         }
  #       } and return
  #     end
  #   end
  # end

  # DELETE /resource/sign_out
  def destroy
    head 200
  end
  # def destroy
  #   super do
  #     if request.format.json?
  #       render :json => {
  #         'csrf_param' => request_forgery_protection_token,
  #         'csrf_token' => form_authenticity_token
  #       }
  #       return
  #     end
  #   end
  # end
 
  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user

  def index
    @users = User.all
  end

  def show
    @is_followed = Relationship.exists?(follower_id: current_user.id, followed_id: @user.id)
  end

  def edit

  end

  def update
    params[:image] ||= @user.image
    if @user.update_attributes(user_params)
    else
    end
    render 'show'
  end

  def follow
    @followed = User.find(params[:id])
    @user.follow(@followed)
    redirect_to user_path(@followed)
  end

  def unfollow
    @followed = User.find(params[:id])
    @user.unfollow(@followed)
    redirect_to user_path(@followed)
  end

  def following
    @is_followed = Relationship.exists?(follower_id: current_user.id, followed_id: @user.id)
  end

  def followers
    @is_followed = Relationship.exists?(follower_id: current_user.id, followed_id: @user.id)
  end

  def favorite
    @user = User.find_by(id: params[:user_id])
    @user.favorite(Post.find(params[:post_id]))
    redirect_to user_post_path(params[:user_id], params[:post_id])
  end

  def unfavorite
    @user = User.find_by(id: params[:user_id])
    @user.unfavorite(Post.find(params[:post_id]))
    redirect_to user_post_path(params[:user_id], params[:post_id])
  end

  def favorite_posts

  end

  private
    def set_user
      @user = User.find_by(id: params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :email, :text, :image)
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/shared/_footer.html.erb
<div class="float-button">
    <% if current_user %>
      <a href='#' class="button-circle"><i class="fas fa-search fa-2x"></i></a>
      <a href='<%= new_user_post_path(current_user) %>' class="button-circle"><i class="fas fa-plus-circle fa-2x"></i></a>
    <% end %>
</div>

app/views/users/shared/_header.html.erb
<header class="header">
    <i class="fas fa-utensils"></i>
      <h1><a href='<%= root_path %>'>Instagourmet</a></h1>
      <% if current_user %>
        <%= link_to "ログアウト", destroy_user_session_path, method: "delete", class: "login-out button" %>
      <% else %>
        <%= link_to "ログイン", new_user_session_path, method: "get", class: "login-out button" %>
      <% end %>
</header>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
  <a href="<%= favorite_posts_user_path(@user) %>">
    <strong id="favorites" class="stat">
      <%= @user.favorite_posts.count %>
    </strong>
    favorites
  </a>
</div>

app/views/users/shared/_user_info.html.erb
<div class="user-info">
    <div class="left">
       <%= image_tag(@user.image, class: 'user-icon') %>
        <p class="user-name"><%= @user.name %></p>
    </div>
    <div class="right">
      <a href="<%= following_user_path(@user) %>" class="button">
          フォロー <%= @user.following.count %>
      </a>
      <a href="<%= followers_user_path(@user) %>" class="button">
          フォロワー <%= @user.followers.count %>
      </a>
        <% if current_user %>
          <% if @user == current_user%>
            <%= link_to '編集', edit_user_path, class: 'button' %>
          <% elsif @is_followed %>
            <%= link_to 'フォローをやめる', unfollow_user_path(current_user, @user), method: :post, class: 'button' %>
          <% else %>
            <%= link_to 'フォローする', follow_user_path(current_user, @user), method: :post, class: 'button' %>
          <% end %>
        <% end %>
        <p>
            <%= @user.text %>
        </p>
    </div>
</div>