config/routes.rb
Rails.application.routes.draw do
  match '*path' => 'options_request#preflight', via: :options

  devise_for :user, only: []

  namespace :api, defaults: { format: :json } do
    resource :login, only: [:create], controller: :sessions
    resource :users, only: [:create]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # resources :users do
  #   member do
  #     get :following, :followers
  #     get :favorite_posts
  #     post 'follow', to: 'users#follow'
  #     post 'unfollow', to: 'users#unfollow'
  #   end
  #   resources :posts do
  #     post 'favorite', to: 'users#favorite'
  #     post 'unfavorite', to: 'users#unfavorite'
  #   end
  # end

  # API
  namespace :api, format: 'json' do
    post '/users/follow/:user_id', to: 'users#follow'
    post '/users/unfollow/:user_id', to: 'users#unfollow'
    get '/users/isfollowing/:user_id', to: 'users#following?'
    post '/users/favorite/:post_id', to: 'users#favorite'
    post '/users/unfavorite/:post_id', to: 'users#unfavorite'
    get '/users/isfavorite/:post_id', to: 'users#favorite?'

    resources :users, only: [:index, :show] do
        get :following, :followers
        get :favorite_posts
      resources :posts, only: [:index, :show, :create] do
      end
    end
  end

  root to: 'home#index'

end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :photo, PhotoUploader

  belongs_to :user
  has_many :favorites
  has_many :favorite_user, :through => :favorites, source: :user
end

app/controllers/api/posts_controller.rb
class Api::PostsController < ApplicationController
  skip_before_action :authenticate_user_from_token!, only: [:index, :show]

  def index
    @posts = User.find(params[:user_id]).posts
    render :json => @posts
  end

  def show

  end

  def create
    @post = Post.new(post_params)
    # @user = User.find(params[:user_id])
    # @user.posts.create!(post_params)
    if @post
      render json: @post, status => 200
    else
      render json: { error: t('post_create_error') }, status: :unprocessable_entity
    end
  end

  def favorite_post
    @user = User.find_by(id: params[:user_id])
    @posts = @user.favorite_posts
    render :json => @posts
  end

  private
    def post_params
      params.require(:post).permit(:text, :user_id, :photo)
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new()
  end

  def create
    @post = Post.new(post_params)
    @post.save
    redirect_to user_path(params[:user_id])
  end

  private
    def post_params
      params.require(:post).permit(:text, :user_id, :photo)
    end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/new.html.erb
<h2>新規投稿</h2>

<%= form_for(@post, url: user_posts_path, html: { method: :post }) do |f| %>

  <div class="field">
    <%= f.label :photo %><br />
    <%= f.file_field :photo %>
  </div>

  <div class="field">
    <%= f.label :text %><br />
    <%= f.text_field :text %>
  </div>

   <div class="field">
    <%= f.hidden_field :user_id, :value => params[:user_id] %><br />
  </div>

  <div class="actions">
    <%= f.submit "create" %>
  </div>
<% end %>

app/views/posts/show.html.erb
<% if current_user.favorite?(@post) %>
  <%= link_to '食べたくない!', user_post_unfavorite_path(current_user, @post.id), method: :post, class: 'button button-on' %>
<% else %>
  <%= link_to '食べたい!', user_post_favorite_path(current_user, @post.id), method: :post, class: 'button' %>
<% end %>
<%= image_tag(@post.photo.url, class: 'post-image') %>
<%= @post.text %>